// Code generated by tools/generate_go_dtos.py. DO NOT EDIT.

package dto

import (
	"encoding/json"
)

// ActiveScopeRequest generated from OpenAPI schema.
type ActiveScopeRequest struct {
	ActiveScope string  `json:"active_scope"`
	ScopeName   *string `json:"scope_name,omitempty"`
}

// ArcGenerateRequest generated from OpenAPI schema.
type ArcGenerateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	FromTurn *int `json:"from_turn,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	ToTurn *int `json:"to_turn,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ArcGenerateRequest.
func (dto *ArcGenerateRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.FromTurn == nil {
		v := 0
		dto.FromTurn = &v
	}
	if dto.ToTurn == nil {
		v := 0
		dto.ToTurn = &v
	}
}

// ChapterDryRunRequest generated from OpenAPI schema.
type ChapterDryRunRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (60): Go handler must apply default when field is absent in request.
	Interval *int `json:"interval,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	TurnIndex *int `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChapterDryRunRequest.
func (dto *ChapterDryRunRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.Interval == nil {
		v := 60
		dto.Interval = &v
	}
	if dto.TurnIndex == nil {
		v := 0
		dto.TurnIndex = &v
	}
}

// ChapterGenerateRequest generated from OpenAPI schema.
type ChapterGenerateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	FromTurn *int `json:"from_turn,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	ToTurn *int `json:"to_turn,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChapterGenerateRequest.
func (dto *ChapterGenerateRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.FromTurn == nil {
		v := 0
		dto.FromTurn = &v
	}
	if dto.ToTurn == nil {
		v := 0
		dto.ToTurn = &v
	}
}

// ChapterSearchRequest generated from OpenAPI schema.
type ChapterSearchRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Query *string `json:"query,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (3): Go handler must apply default when field is absent in request.
	TopK *int `json:"top_k,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChapterSearchRequest.
func (dto *ChapterSearchRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Query == nil {
		v := ""
		dto.Query = &v
	}
	if dto.TopK == nil {
		v := 3
		dto.TopK = &v
	}
}

// ChatLogRepairEntryRequest generated from OpenAPI schema.
type ChatLogRepairEntryRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantContent *string `json:"assistant_content,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantContentHash *string `json:"assistant_content_hash,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantGenerationID *string `json:"assistant_generation_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantMessageID *string `json:"assistant_message_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	CreatedAt *string `json:"created_at,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	InputMode *string `json:"input_mode,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Source    *string `json:"source,omitempty"`
	TurnIndex int     `json:"turn_index"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	UserContent *string `json:"user_content,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	UserInputState *string `json:"user_input_state,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChatLogRepairEntryRequest.
func (dto *ChatLogRepairEntryRequest) ApplyDefaults() {
	if dto.AssistantContent == nil {
		v := ""
		dto.AssistantContent = &v
	}
	if dto.AssistantContentHash == nil {
		v := ""
		dto.AssistantContentHash = &v
	}
	if dto.AssistantGenerationID == nil {
		v := ""
		dto.AssistantGenerationID = &v
	}
	if dto.AssistantMessageID == nil {
		v := ""
		dto.AssistantMessageID = &v
	}
	if dto.CreatedAt == nil {
		v := ""
		dto.CreatedAt = &v
	}
	if dto.InputMode == nil {
		v := ""
		dto.InputMode = &v
	}
	if dto.Source == nil {
		v := ""
		dto.Source = &v
	}
	if dto.UserContent == nil {
		v := ""
		dto.UserContent = &v
	}
	if dto.UserInputState == nil {
		v := ""
		dto.UserInputState = &v
	}
}

// ChatLogRepairReplayRequest generated from OpenAPI schema.
type ChatLogRepairReplayRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	DryRun  *bool                       `json:"dry_run,omitempty"`
	Entries []ChatLogRepairEntryRequest `json:"entries,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChatLogRepairReplayRequest.
func (dto *ChatLogRepairReplayRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.DryRun == nil {
		v := false
		dto.DryRun = &v
	}
}

// ChromaShadowAdoptionGateRequest generated from OpenAPI schema.
type ChromaShadowAdoptionGateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID    *string        `json:"chat_session_id,omitempty"`
	OperatorEvidence map[string]any `json:"operator_evidence,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowAdoptionGateRequest.
func (dto *ChromaShadowAdoptionGateRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// ChromaShadowBackfillBatchRequest generated from OpenAPI schema.
type ChromaShadowBackfillBatchRequest struct {
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (25): Go handler must apply default when field is absent in request.
	BatchSizePerTier *int64 `json:"batch_size_per_tier,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string          `json:"chat_session_id,omitempty"`
	Checkpoint    map[string]any   `json:"checkpoint,omitempty"`
	RetryRows     []map[string]any `json:"retry_rows,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowBackfillBatchRequest.
func (dto *ChromaShadowBackfillBatchRequest) ApplyDefaults() {
	if dto.BatchSizePerTier == nil {
		v := int64(25)
		dto.BatchSizePerTier = &v
	}
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// ChromaShadowBackfillDryRunRequest generated from OpenAPI schema.
type ChromaShadowBackfillDryRunRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (2): Go handler must apply default when field is absent in request.
	SampleLimitPerTier *int64 `json:"sample_limit_per_tier,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowBackfillDryRunRequest.
func (dto *ChromaShadowBackfillDryRunRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.SampleLimitPerTier == nil {
		v := int64(2)
		dto.SampleLimitPerTier = &v
	}
}

// ChromaShadowFallbackRunbookRequest generated from OpenAPI schema.
type ChromaShadowFallbackRunbookRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowFallbackRunbookRequest.
func (dto *ChromaShadowFallbackRunbookRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// ChromaShadowHealthProbeRequest generated from OpenAPI schema.
type ChromaShadowHealthProbeRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowHealthProbeRequest.
func (dto *ChromaShadowHealthProbeRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// ChromaShadowRebuildDrillRequest generated from OpenAPI schema.
type ChromaShadowRebuildDrillRequest struct {
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (25): Go handler must apply default when field is absent in request.
	BatchSizePerTier *int64 `json:"batch_size_per_tier,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string        `json:"chat_session_id,omitempty"`
	Checkpoint    map[string]any `json:"checkpoint,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	ExecuteRebuildThenRollback *bool            `json:"execute_rebuild_then_rollback,omitempty"`
	RetryRows                  []map[string]any `json:"retry_rows,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowRebuildDrillRequest.
func (dto *ChromaShadowRebuildDrillRequest) ApplyDefaults() {
	if dto.BatchSizePerTier == nil {
		v := int64(25)
		dto.BatchSizePerTier = &v
	}
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.ExecuteRebuildThenRollback == nil {
		v := false
		dto.ExecuteRebuildThenRollback = &v
	}
}

// ChromaShadowReembedAuditRequest generated from OpenAPI schema.
type ChromaShadowReembedAuditRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (25): Go handler must apply default when field is absent in request.
	QueueLimitPerTier *int64 `json:"queue_limit_per_tier,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowReembedAuditRequest.
func (dto *ChromaShadowReembedAuditRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.QueueLimitPerTier == nil {
		v := int64(25)
		dto.QueueLimitPerTier = &v
	}
}

// ChromaShadowReleaseHygieneRequest generated from OpenAPI schema.
type ChromaShadowReleaseHygieneRequest struct {
	AdoptionOperatorEvidence map[string]any `json:"adoption_operator_evidence,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID   *string        `json:"chat_session_id,omitempty"`
	ReleaseEvidence map[string]any `json:"release_evidence,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowReleaseHygieneRequest.
func (dto *ChromaShadowReleaseHygieneRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// ChromaShadowVisibilityGuardRequest generated from OpenAPI schema.
type ChromaShadowVisibilityGuardRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (20): Go handler must apply default when field is absent in request.
	SampleLimit *int64 `json:"sample_limit,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ChromaShadowVisibilityGuardRequest.
func (dto *ChromaShadowVisibilityGuardRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.SampleLimit == nil {
		v := int64(20)
		dto.SampleLimit = &v
	}
}

// CompleteTurnRequest generated from OpenAPI schema.
type CompleteTurnRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID          *string          `json:"chat_session_id,omitempty"`
	Context                []map[string]any `json:"context,omitempty"`
	OutputLanguageOverride *map[string]any  `json:"output_language_override,omitempty"`
	TurnContent            string           `json:"turn_content"`
	TurnIndex              int              `json:"turn_index"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in CompleteTurnRequest.
func (dto *CompleteTurnRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// CriticTestRequest generated from OpenAPI schema.
type CriticTestRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID          *string          `json:"chat_session_id,omitempty"`
	Context                []map[string]any `json:"context,omitempty"`
	OutputLanguageOverride *map[string]any  `json:"output_language_override,omitempty"`
	TurnContent            string           `json:"turn_content"`
	TurnIndex              int              `json:"turn_index"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in CriticTestRequest.
func (dto *CriticTestRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// DirectEvidenceRevalidateRequest generated from OpenAPI schema.
type DirectEvidenceRevalidateRequest struct {
	ChatSessionID string  `json:"chat_session_id"`
	ReviewNote    *string `json:"review_note,omitempty"`
}

// DirectorPatchRequest generated from OpenAPI schema.
type DirectorPatchRequest struct {
	ExecutionChecklist *[]string `json:"execution_checklist,omitempty"`
	ForbiddenMoves     *[]string `json:"forbidden_moves,omitempty"`
	PersonaGuardrails  *[]string `json:"persona_guardrails,omitempty"`
	PressureLevel      *string   `json:"pressure_level,omitempty"`
	RequiredOutcomes   *[]string `json:"required_outcomes,omitempty"`
	SceneMandate       *string   `json:"scene_mandate,omitempty"`
	WorldGuardrails    *[]string `json:"world_guardrails,omitempty"`
}

// EpisodeGenerateRequest generated from OpenAPI schema.
type EpisodeGenerateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	FromTurn *int `json:"from_turn,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	ToTurn *int `json:"to_turn,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in EpisodeGenerateRequest.
func (dto *EpisodeGenerateRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.FromTurn == nil {
		v := 0
		dto.FromTurn = &v
	}
	if dto.ToTurn == nil {
		v := 0
		dto.ToTurn = &v
	}
}

// EpisodeMergeRequest generated from OpenAPI schema.
type EpisodeMergeRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	EpisodeIds    []int   `json:"episode_ids,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in EpisodeMergeRequest.
func (dto *EpisodeMergeRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
}

// EpisodeSearchRequest generated from OpenAPI schema.
type EpisodeSearchRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Query *string `json:"query,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (3): Go handler must apply default when field is absent in request.
	TopK *int `json:"top_k,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in EpisodeSearchRequest.
func (dto *EpisodeSearchRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Query == nil {
		v := ""
		dto.Query = &v
	}
	if dto.TopK == nil {
		v := 3
		dto.TopK = &v
	}
}

// FeedbackRequest generated from OpenAPI schema.
type FeedbackRequest struct {
	ChatSessionID string  `json:"chat_session_id"`
	FeedbackNote  *string `json:"feedback_note,omitempty"`
	FeedbackValue string  `json:"feedback_value"`
	TargetID      int64   `json:"target_id"`
	TargetType    string  `json:"target_type"`
}

// HTTPValidationError generated from OpenAPI schema.
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// HypaImportRequest generated from OpenAPI schema.
type HypaImportRequest struct {
	ChatSessionID string              `json:"chat_session_id"`
	Summaries     []HypaImportSummary `json:"summaries"`
}

// HypaImportSummary generated from OpenAPI schema.
type HypaImportSummary struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Category *string `json:"category,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	IsImportant     *bool    `json:"is_important,omitempty"`
	SourceTurnIndex *int     `json:"source_turn_index,omitempty"`
	Tags            []string `json:"tags,omitempty"`
	Text            string   `json:"text"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in HypaImportSummary.
func (dto *HypaImportSummary) ApplyDefaults() {
	if dto.Category == nil {
		v := ""
		dto.Category = &v
	}
	if dto.IsImportant == nil {
		v := false
		dto.IsImportant = &v
	}
}

// IntentRoutingRuntimeConfigRequest generated from OpenAPI schema.
type IntentRoutingRuntimeConfigRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("single_query_shared"): Go handler must apply default when field is absent in request.
	Mode *string `json:"mode,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in IntentRoutingRuntimeConfigRequest.
func (dto *IntentRoutingRuntimeConfigRequest) ApplyDefaults() {
	if dto.Mode == nil {
		v := "single_query_shared"
		dto.Mode = &v
	}
}

// KGRecallRequest generated from OpenAPI schema.
type KGRecallRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string  `json:"chat_session_id,omitempty"`
	CurrentTurn   *int     `json:"current_turn,omitempty"`
	Entities      []string `json:"entities,omitempty"`
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (20): Go handler must apply default when field is absent in request.
	Limit *int64 `json:"limit,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in KGRecallRequest.
func (dto *KGRecallRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Limit == nil {
		v := int64(20)
		dto.Limit = &v
	}
}

// M4CompleteTurnRequest generated from OpenAPI schema.
type M4CompleteTurnRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantContent       *string          `json:"assistant_content,omitempty"`
	ChatSessionID          string           `json:"chat_session_id"`
	ClientMeta             map[string]any   `json:"client_meta,omitempty"`
	ContextMessages        []map[string]any `json:"context_messages,omitempty"`
	ImprovementTrace       *map[string]any  `json:"improvement_trace,omitempty"`
	OutputLanguageOverride *map[string]any  `json:"output_language_override,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("model"): Go handler must apply default when field is absent in request.
	RequestType *string `json:"request_type,omitempty"`
	TurnIndex   int     `json:"turn_index"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	UserInput *string `json:"user_input,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in M4CompleteTurnRequest.
func (dto *M4CompleteTurnRequest) ApplyDefaults() {
	if dto.AssistantContent == nil {
		v := ""
		dto.AssistantContent = &v
	}
	if dto.RequestType == nil {
		v := "model"
		dto.RequestType = &v
	}
	if dto.UserInput == nil {
		v := ""
		dto.UserInput = &v
	}
}

// M4CompleteTurnResponse generated from OpenAPI schema.
type M4CompleteTurnResponse struct {
	ChapterResult *map[string]any `json:"chapter_result,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string         `json:"chat_session_id,omitempty"`
	CriticResult  *map[string]any `json:"critic_result,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	CriticTriggered *bool           `json:"critic_triggered,omitempty"`
	EpisodeResult   *map[string]any `json:"episode_result,omitempty"`
	FailReasons     []string        `json:"fail_reasons,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	GeneratedAt *string `json:"generated_at,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	MaintenanceEnqueued *bool   `json:"maintenance_enqueued,omitempty"`
	SaveError           *string `json:"save_error,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	SaveOk *bool `json:"save_ok,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("ok"): Go handler must apply default when field is absent in request.
	Status          *string         `json:"status,omitempty"`
	SummaryFallback *map[string]any `json:"summary_fallback,omitempty"`
	TraceHandoff    *map[string]any `json:"trace_handoff,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	TurnIndex *int     `json:"turn_index,omitempty"`
	Warnings  []string `json:"warnings,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in M4CompleteTurnResponse.
func (dto *M4CompleteTurnResponse) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.CriticTriggered == nil {
		v := false
		dto.CriticTriggered = &v
	}
	if dto.GeneratedAt == nil {
		v := ""
		dto.GeneratedAt = &v
	}
	if dto.MaintenanceEnqueued == nil {
		v := false
		dto.MaintenanceEnqueued = &v
	}
	if dto.SaveOk == nil {
		v := false
		dto.SaveOk = &v
	}
	if dto.Status == nil {
		v := "ok"
		dto.Status = &v
	}
	if dto.TurnIndex == nil {
		v := 0
		dto.TurnIndex = &v
	}
}

// MaintenanceEnqueueRequest generated from OpenAPI schema.
type MaintenanceEnqueueRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantResponse *string  `json:"assistant_response,omitempty"`
	ChatSessionID     string   `json:"chat_session_id"`
	RecentResponses   []string `json:"recent_responses,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	ShadowOnly       *bool           `json:"shadow_only,omitempty"`
	SummaryRefresh   *map[string]any `json:"summary_refresh,omitempty"`
	SupervisorResult *map[string]any `json:"supervisor_result,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (-1): Go handler must apply default when field is absent in request.
	TurnIndex *int `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in MaintenanceEnqueueRequest.
func (dto *MaintenanceEnqueueRequest) ApplyDefaults() {
	if dto.AssistantResponse == nil {
		v := ""
		dto.AssistantResponse = &v
	}
	if dto.ShadowOnly == nil {
		v := true
		dto.ShadowOnly = &v
	}
	if dto.TurnIndex == nil {
		v := -1
		dto.TurnIndex = &v
	}
}

// MaintenanceEnqueueResponse generated from OpenAPI schema.
type MaintenanceEnqueueResponse struct {
	ChatSessionID string `json:"chat_session_id"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	QueueDepth *int   `json:"queue_depth,omitempty"`
	Status     string `json:"status"`
	TurnIndex  int    `json:"turn_index"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in MaintenanceEnqueueResponse.
func (dto *MaintenanceEnqueueResponse) ApplyDefaults() {
	if dto.QueueDepth == nil {
		v := 0
		dto.QueueDepth = &v
	}
}

// MaintenancePassRequest generated from OpenAPI schema.
type MaintenancePassRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantResponse *string  `json:"assistant_response,omitempty"`
	RecentResponses   []string `json:"recent_responses,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	ShadowOnly       *bool           `json:"shadow_only,omitempty"`
	SupervisorResult *map[string]any `json:"supervisor_result,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (-1): Go handler must apply default when field is absent in request.
	TurnIndex *int `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in MaintenancePassRequest.
func (dto *MaintenancePassRequest) ApplyDefaults() {
	if dto.AssistantResponse == nil {
		v := ""
		dto.AssistantResponse = &v
	}
	if dto.ShadowOnly == nil {
		v := true
		dto.ShadowOnly = &v
	}
	if dto.TurnIndex == nil {
		v := -1
		dto.TurnIndex = &v
	}
}

// PatchCharacterRequest generated from OpenAPI schema.
type PatchCharacterRequest struct {
	AppearanceJSON    *string `json:"appearance_json,omitempty"`
	PersonalityJSON   *string `json:"personality_json,omitempty"`
	RelationshipsJSON *string `json:"relationships_json,omitempty"`
	SpeechStyleJSON   *string `json:"speech_style_json,omitempty"`
	StatusJSON        *string `json:"status_json,omitempty"`
}

// PatchDirectEvidenceReviewRequest generated from OpenAPI schema.
type PatchDirectEvidenceReviewRequest struct {
	ArchiveState        *string `json:"archive_state,omitempty"`
	CaptureVerification *string `json:"capture_verification,omitempty"`
	ChatSessionID       string  `json:"chat_session_id"`
	CommittedGate       *string `json:"committed_gate,omitempty"`
	RepairNeeded        *bool   `json:"repair_needed,omitempty"`
	ReviewNote          *string `json:"review_note,omitempty"`
}

// PatchDirectEvidenceSupersedeRequest generated from OpenAPI schema.
type PatchDirectEvidenceSupersedeRequest struct {
	ChatSessionID  string  `json:"chat_session_id"`
	ReviewNote     *string `json:"review_note,omitempty"`
	SupersededByID int64   `json:"superseded_by_id"`
}

// PatchDirectEvidenceTombstoneRequest generated from OpenAPI schema.
type PatchDirectEvidenceTombstoneRequest struct {
	ChatSessionID string  `json:"chat_session_id"`
	ReviewNote    *string `json:"review_note,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	Tombstoned *bool `json:"tombstoned,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in PatchDirectEvidenceTombstoneRequest.
func (dto *PatchDirectEvidenceTombstoneRequest) ApplyDefaults() {
	if dto.Tombstoned == nil {
		v := true
		dto.Tombstoned = &v
	}
}

// PatchEpisodeRequest generated from OpenAPI schema.
type PatchEpisodeRequest struct {
	FromTurn                *int    `json:"from_turn,omitempty"`
	KeyEntities             *string `json:"key_entities,omitempty"`
	KeyEvents               *string `json:"key_events,omitempty"`
	OpenLoopsJSON           *string `json:"open_loops_json,omitempty"`
	RelationshipChangesJSON *string `json:"relationship_changes_json,omitempty"`
	SummaryText             *string `json:"summary_text,omitempty"`
	ToTurn                  *int    `json:"to_turn,omitempty"`
}

// PatchKGTripleRequest generated from OpenAPI schema.
type PatchKGTripleRequest struct {
	ChatSessionID string  `json:"chat_session_id"`
	Object        *string `json:"object,omitempty"`
	Predicate     *string `json:"predicate,omitempty"`
	Subject       *string `json:"subject,omitempty"`
	// BLOCKER: PatchKGTripleRequest.properties.valid_from: non-null union anyOf
	ValidFrom json.RawMessage `json:"valid_from,omitempty"`
	// BLOCKER: PatchKGTripleRequest.properties.valid_to: non-null union anyOf
	ValidTo json.RawMessage `json:"valid_to,omitempty"`
}

// PatchMemoryRequest generated from OpenAPI schema.
type PatchMemoryRequest struct {
	ArchiveRoom   *string  `json:"archive_room,omitempty"`
	ArchiveWing   *string  `json:"archive_wing,omitempty"`
	ChatSessionID string   `json:"chat_session_id"`
	Importance    *float64 `json:"importance,omitempty"`
	SummaryJSON   *string  `json:"summary_json,omitempty"`
}

// PatchPendingThreadRequest generated from OpenAPI schema.
type PatchPendingThreadRequest struct {
	Confidence     *float64 `json:"confidence,omitempty"`
	DetailsJSON    *string  `json:"details_json,omitempty"`
	Owner          *string  `json:"owner,omitempty"`
	ResolutionNote *string  `json:"resolution_note,omitempty"`
	Status         *string  `json:"status,omitempty"`
	Target         *string  `json:"target,omitempty"`
	ThreadType     *string  `json:"thread_type,omitempty"`
	Title          *string  `json:"title,omitempty"`
}

// PatchSpeechStyleRequest generated from OpenAPI schema.
type PatchSpeechStyleRequest struct {
	DefaultTone    *string `json:"default_tone,omitempty"`
	HonorificStyle *string `json:"honorific_style,omitempty"`
	SpeechNotes    *string `json:"speech_notes,omitempty"`
}

// PatchStorylineRequest generated from OpenAPI schema.
type PatchStorylineRequest struct {
	Confidence          *float64 `json:"confidence,omitempty"`
	CurrentContext      *string  `json:"current_context,omitempty"`
	EntitiesJSON        *string  `json:"entities_json,omitempty"`
	EvidenceCount       *int64   `json:"evidence_count,omitempty"`
	FirstTurn           *int     `json:"first_turn,omitempty"`
	KeyPointsJSON       *string  `json:"key_points_json,omitempty"`
	LastEvidenceTurn    *int     `json:"last_evidence_turn,omitempty"`
	LastTurn            *int     `json:"last_turn,omitempty"`
	Name                *string  `json:"name,omitempty"`
	OngoingTensionsJSON *string  `json:"ongoing_tensions_json,omitempty"`
	Status              *string  `json:"status,omitempty"`
}

// PatchWorldRuleRequest generated from OpenAPI schema.
type PatchWorldRuleRequest struct {
	Category  *string `json:"category,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	Key       *string `json:"key,omitempty"`
	Scope     *string `json:"scope,omitempty"`
	ScopeName *string `json:"scope_name,omitempty"`
	ValueJSON *string `json:"value_json,omitempty"`
}

// PrepareTurnRequest generated from OpenAPI schema.
type PrepareTurnRequest struct {
	ChatSessionID string         `json:"chat_session_id"`
	ClientMeta    map[string]any `json:"client_meta,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ContinuityQuery *string `json:"continuity_query,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("none"): Go handler must apply default when field is absent in request.
	ContinuityTriggerMode *string          `json:"continuity_trigger_mode,omitempty"`
	Messages              []map[string]any `json:"messages,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	RawUserInput *string `json:"raw_user_input,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("model"): Go handler must apply default when field is absent in request.
	RequestType *string             `json:"request_type,omitempty"`
	Settings    PrepareTurnSettings `json:"settings,omitempty"`
	TurnIndex   *int                `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in PrepareTurnRequest.
func (dto *PrepareTurnRequest) ApplyDefaults() {
	if dto.ContinuityQuery == nil {
		v := ""
		dto.ContinuityQuery = &v
	}
	if dto.ContinuityTriggerMode == nil {
		v := "none"
		dto.ContinuityTriggerMode = &v
	}
	if dto.RawUserInput == nil {
		v := ""
		dto.RawUserInput = &v
	}
	if dto.RequestType == nil {
		v := "model"
		dto.RequestType = &v
	}
}

// PrepareTurnSettings generated from OpenAPI schema.
type PrepareTurnSettings struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("shadow"): Go handler must apply default when field is absent in request.
	ApplyMode *string `json:"apply_mode,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (10): Go handler must apply default when field is absent in request.
	EpisodeIntervalTurns *int `json:"episode_interval_turns,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("off"): Go handler must apply default when field is absent in request.
	GuideMode *string `json:"guide_mode,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("weak"): Go handler must apply default when field is absent in request.
	GuideStrength *string `json:"guide_strength,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	InjectionEnabled *bool `json:"injection_enabled,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	InputContextEnabled *bool `json:"input_context_enabled,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (18000): Go handler must apply default when field is absent in request.
	MaxInjectionChars *int `json:"max_injection_chars,omitempty"`
	// MemoryTransportMode selects the representation of the already-selected long-term-memory lane.
	// DEFAULT: text preserves the existing payload path.
	MemoryTransportMode *string `json:"memory_transport_mode,omitempty"`
	// MemoryDeliveryBudgetMode selects automatic profile budgets or user-supplied per-class reservations.
	MemoryDeliveryBudgetMode *string `json:"memory_delivery_budget_mode,omitempty"`
	// MemoryDeliveryBudgets carries character reservations for the seven Go-owned delivery classes.
	MemoryDeliveryBudgets map[string]int `json:"memory_delivery_budgets,omitempty"`
	// TurnFinalizationMode selects immediate persistence or previous-turn persistence at the next user input.
	// DEFAULT: immediate_after_response preserves the 4.1 lifecycle.
	TurnFinalizationMode *string `json:"turn_finalization_mode,omitempty"`
	// LorebookReferenceMode controls the separate read-only Host lorebook reference lane.
	// Missing values default to reference_assist; the lorebook remains bounded support, not primary memory authority.
	LorebookReferenceMode *string `json:"lorebook_reference_mode,omitempty"`
	// PRESENCE: Optional non-null scalar int carrying the independent Host lorebook reference cap.
	// DEFAULT: Optional field with default (3000): Go handler must apply default when field is absent in request.
	LorebookReferenceMaxChars *int `json:"lorebook_reference_max_chars,omitempty"`
	// PRESENCE: Optional non-null scalar int controlling only the final objective-event memory item ceiling.
	// DEFAULT: No default: absent callers preserve the legacy character-budget-only delivery behavior.
	// Legacy wire key: per-group core priority target; remaining facts use the character budget.
	CoreObjectiveMemoryMaxItems *int `json:"core_objective_memory_max_items,omitempty"`
	// PRESENCE: Optional non-null scalar int carrying the independent original-work reference cap.
	// DEFAULT: Optional field with default (3000): Go handler must apply default when field is absent in request.
	ReferenceInjectionBudgetBasisChars *int `json:"reference_injection_budget_basis_chars,omitempty"`
	// PRESENCE: Optional non-null scalar int controlling only the reference recall candidate limit.
	// DEFAULT: No default: absent callers inherit the effective top_k for compatibility; explicit zero disables reference recall candidates.
	ReferenceRecallLimit *int `json:"reference_recall_limit,omitempty"`
	// PRESENCE: Optional non-null scalar bool controlling only the independent reference lane.
	// DEFAULT: No default: absent callers inherit injection_enabled for compatibility.
	ReferenceInjectionEnabled *bool `json:"reference_injection_enabled,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type because zero disables Primary Canon Base.
	// DEFAULT: No default: absent and explicit zero remain disabled and must not borrow another injection budget.
	PrimaryCanonBaseMaxChars *int `json:"primary_canon_base_max_chars,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (800): Go handler must apply default when field is absent in request.
	MaxInputContextChars *int `json:"max_input_context_chars,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("balanced"): Go handler must apply default when field is absent in request.
	NarrativeStance *string `json:"narrative_stance,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (true): Go handler must apply default when field is absent in request.
	SupervisorEnabled *bool `json:"supervisor_enabled,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("off"): Go handler must apply default when field is absent in request.
	TakeoverMode *string `json:"takeover_mode,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (5): Go handler must apply default when field is absent in request.
	RecentConversationReferenceCount *int `json:"recent_conversation_reference_count,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (5): Go handler must apply default when field is absent in request.
	TopK *int `json:"top_k,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in PrepareTurnSettings.
func (dto *PrepareTurnSettings) ApplyDefaults() {
	if dto.ApplyMode == nil {
		v := "shadow"
		dto.ApplyMode = &v
	}
	if dto.EpisodeIntervalTurns == nil {
		v := 10
		dto.EpisodeIntervalTurns = &v
	}
	if dto.GuideMode == nil {
		v := "off"
		dto.GuideMode = &v
	}
	if dto.GuideStrength == nil {
		v := "weak"
		dto.GuideStrength = &v
	}
	if dto.InjectionEnabled == nil {
		v := true
		dto.InjectionEnabled = &v
	}
	if dto.InputContextEnabled == nil {
		v := true
		dto.InputContextEnabled = &v
	}
	if dto.MaxInjectionChars == nil {
		v := 18000
		dto.MaxInjectionChars = &v
	}
	if dto.MemoryTransportMode == nil {
		v := "text"
		dto.MemoryTransportMode = &v
	}
	if dto.TurnFinalizationMode == nil {
		v := "immediate_after_response"
		dto.TurnFinalizationMode = &v
	}
	if dto.LorebookReferenceMode == nil {
		v := "reference_assist"
		dto.LorebookReferenceMode = &v
	}
	if dto.LorebookReferenceMaxChars == nil {
		v := 3000
		dto.LorebookReferenceMaxChars = &v
	}
	if dto.ReferenceInjectionBudgetBasisChars == nil {
		v := 3000
		dto.ReferenceInjectionBudgetBasisChars = &v
	}
	if dto.MaxInputContextChars == nil {
		v := 800
		dto.MaxInputContextChars = &v
	}
	if dto.NarrativeStance == nil {
		v := "balanced"
		dto.NarrativeStance = &v
	}
	if dto.SupervisorEnabled == nil {
		v := true
		dto.SupervisorEnabled = &v
	}
	if dto.TakeoverMode == nil {
		v := "off"
		dto.TakeoverMode = &v
	}
	if dto.RecentConversationReferenceCount == nil {
		v := 5
		dto.RecentConversationReferenceCount = &v
	}
	if dto.TopK == nil {
		v := 5
		dto.TopK = &v
	}
}

// PromptUpdateRequest generated from OpenAPI schema.
type PromptUpdateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Content *string `json:"content,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in PromptUpdateRequest.
func (dto *PromptUpdateRequest) ApplyDefaults() {
	if dto.Content == nil {
		v := ""
		dto.Content = &v
	}
}

// ProxyPluginMainRequest generated from OpenAPI schema.
type ProxyPluginMainRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	APIKey       *string `json:"api_key,omitempty"`
	BudgetTokens *int64  `json:"budget_tokens,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Endpoint              *string `json:"endpoint,omitempty"`
	ClaudePromptCacheMode *string `json:"claude_prompt_cache_mode,omitempty"`
	ExtraBodyJSON         *string `json:"extra_body_json,omitempty"`
	ExtraHeadersJSON      *string `json:"extra_headers_json,omitempty"`
	GlmThinkingType       *string `json:"glm_thinking_type,omitempty"`
	LLMGatewayServiceTier *string `json:"llm_gateway_service_tier,omitempty"`
	MaxCompletionTokens   *int64  `json:"max_completion_tokens,omitempty"`
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (1024): Go handler must apply default when field is absent in request.
	MaxTokens *int64 `json:"max_tokens,omitempty"`
	// BLOCKER: ProxyPluginMainRequest.properties.messages.items: untyped property
	Messages []any `json:"messages"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	Model                 *string `json:"model,omitempty"`
	Provider              *string `json:"provider,omitempty"`
	ReasoningBudgetTokens *int64  `json:"reasoning_budget_tokens,omitempty"`
	ReasoningEffort       *string `json:"reasoning_effort,omitempty"`
	ReasoningPreset       *string `json:"reasoning_preset,omitempty"`
	// PRESENCE: Optional non-null scalar float64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0.7): Go handler must apply default when field is absent in request.
	Temperature    *float64 `json:"temperature,omitempty"`
	TimeoutMs      *int64   `json:"timeout_ms,omitempty"`
	VertexFlexMode *string  `json:"vertex_flex_mode,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ProxyPluginMainRequest.
func (dto *ProxyPluginMainRequest) ApplyDefaults() {
	if dto.APIKey == nil {
		v := ""
		dto.APIKey = &v
	}
	if dto.Endpoint == nil {
		v := ""
		dto.Endpoint = &v
	}
	if dto.ExtraBodyJSON == nil {
		v := ""
		dto.ExtraBodyJSON = &v
	}
	if dto.ExtraHeadersJSON == nil {
		v := ""
		dto.ExtraHeadersJSON = &v
	}
	if dto.LLMGatewayServiceTier == nil {
		v := ""
		dto.LLMGatewayServiceTier = &v
	}
	if dto.MaxTokens == nil {
		v := int64(1024)
		dto.MaxTokens = &v
	}
	if dto.Model == nil {
		v := ""
		dto.Model = &v
	}
	if dto.Temperature == nil {
		v := 0.7
		dto.Temperature = &v
	}
	if dto.VertexFlexMode == nil {
		v := ""
		dto.VertexFlexMode = &v
	}
}

// ReindexRequest generated from OpenAPI schema.
type ReindexRequest struct {
	// PRESENCE: Optional non-null scalar int64: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (20): Go handler must apply default when field is absent in request.
	BatchSize     *int64 `json:"batch_size,omitempty"`
	ChatSessionID string `json:"chat_session_id"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (200): Go handler must apply default when field is absent in request.
	MaxItems *int `json:"max_items,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in ReindexRequest.
func (dto *ReindexRequest) ApplyDefaults() {
	if dto.BatchSize == nil {
		v := int64(20)
		dto.BatchSize = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.MaxItems == nil {
		v := 200
		dto.MaxItems = &v
	}
}

// RescanRequest generated from OpenAPI schema.
type RescanRequest struct {
	ChatSessionID string `json:"chat_session_id"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (50): Go handler must apply default when field is absent in request.
	MaxItems    *int  `json:"max_items,omitempty"`
	TurnIndices []int `json:"turn_indices,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in RescanRequest.
func (dto *RescanRequest) ApplyDefaults() {
	if dto.MaxItems == nil {
		v := 50
		dto.MaxItems = &v
	}
}

// RetrievalIndexRuntimeConfigRequest generated from OpenAPI schema.
type RetrievalIndexRuntimeConfigRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("shadow"): Go handler must apply default when field is absent in request.
	Mode *string `json:"mode,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in RetrievalIndexRuntimeConfigRequest.
func (dto *RetrievalIndexRuntimeConfigRequest) ApplyDefaults() {
	if dto.Mode == nil {
		v := "shadow"
		dto.Mode = &v
	}
}

// SagaGenerateRequest generated from OpenAPI schema.
type SagaGenerateRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	Force *bool `json:"force,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	FromTurn *int `json:"from_turn,omitempty"`
	// PRESENCE: Optional non-null scalar int: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (0): Go handler must apply default when field is absent in request.
	ToTurn *int `json:"to_turn,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SagaGenerateRequest.
func (dto *SagaGenerateRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Force == nil {
		v := false
		dto.Force = &v
	}
	if dto.FromTurn == nil {
		v := 0
		dto.FromTurn = &v
	}
	if dto.ToTurn == nil {
		v := 0
		dto.ToTurn = &v
	}
}

// SaveEffectiveInputRequest generated from OpenAPI schema.
type SaveEffectiveInputRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	EffectiveInput *string `json:"effective_input,omitempty"`
	TurnIndex      int     `json:"turn_index"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SaveEffectiveInputRequest.
func (dto *SaveEffectiveInputRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.EffectiveInput == nil {
		v := ""
		dto.EffectiveInput = &v
	}
}

// SaveTurnRequest generated from OpenAPI schema.
type SaveTurnRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	AssistantContent *string `json:"assistant_content,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	TurnIndex     int     `json:"turn_index"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	UserContent *string `json:"user_content,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SaveTurnRequest.
func (dto *SaveTurnRequest) ApplyDefaults() {
	if dto.AssistantContent == nil {
		v := ""
		dto.AssistantContent = &v
	}
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.UserContent == nil {
		v := ""
		dto.UserContent = &v
	}
}

// SearchRequest generated from OpenAPI schema.
type SearchRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	TopK          *int    `json:"top_k,omitempty"`
	UserInput     string  `json:"user_input"`
	Wing          *string `json:"wing,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SearchRequest.
func (dto *SearchRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
}

// SessionMigrateRequest generated from OpenAPI schema.
type SessionMigrateRequest struct {
	// PRESENCE: Optional non-null scalar bool: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (false): Go handler must apply default when field is absent in request.
	DryRun          *bool    `json:"dry_run,omitempty"`
	GateConfidence  *float64 `json:"gate_confidence,omitempty"`
	GateReads       *int     `json:"gate_reads,omitempty"`
	GateReason      *string  `json:"gate_reason,omitempty"`
	GateStatus      *string  `json:"gate_status,omitempty"`
	SourceSessionID string   `json:"source_session_id"`
	TargetSessionID string   `json:"target_session_id"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SessionMigrateRequest.
func (dto *SessionMigrateRequest) ApplyDefaults() {
	if dto.DryRun == nil {
		v := false
		dto.DryRun = &v
	}
}

// StorylineSyncRequest generated from OpenAPI schema.
type StorylineSyncRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID *string `json:"chat_session_id,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("dry_run"): Go handler must apply default when field is absent in request.
	Mode             *string        `json:"mode,omitempty"`
	SupervisorResult map[string]any `json:"supervisor_result,omitempty"`
	TurnIndex        *int           `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in StorylineSyncRequest.
func (dto *StorylineSyncRequest) ApplyDefaults() {
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.Mode == nil {
		v := "dry_run"
		dto.Mode = &v
	}
}

// SupervisorRequest generated from OpenAPI schema.
type SupervisorRequest struct {
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("none"): Go handler must apply default when field is absent in request.
	AutoAdvanceTrigger *string `json:"auto_advance_trigger,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	ChatSessionID   *string          `json:"chat_session_id,omitempty"`
	ContextMessages []map[string]any `json:"context_messages,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("off"): Go handler must apply default when field is absent in request.
	GuideMode *string `json:"guide_mode,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	GuideSuffix    *string         `json:"guide_suffix,omitempty"`
	MomentumPacket *map[string]any `json:"momentum_packet,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("balanced"): Go handler must apply default when field is absent in request.
	NarrativeStance       *string        `json:"narrative_stance,omitempty"`
	NarrativeStanceBounds map[string]any `json:"narrative_stance_bounds,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	NarrativeStanceSuffix *string `json:"narrative_stance_suffix,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	PersistentGuidance *string `json:"persistent_guidance,omitempty"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default (""): Go handler must apply default when field is absent in request.
	WakeUpContext *string `json:"wake_up_context,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in SupervisorRequest.
func (dto *SupervisorRequest) ApplyDefaults() {
	if dto.AutoAdvanceTrigger == nil {
		v := "none"
		dto.AutoAdvanceTrigger = &v
	}
	if dto.ChatSessionID == nil {
		v := ""
		dto.ChatSessionID = &v
	}
	if dto.GuideMode == nil {
		v := "off"
		dto.GuideMode = &v
	}
	if dto.GuideSuffix == nil {
		v := ""
		dto.GuideSuffix = &v
	}
	if dto.NarrativeStance == nil {
		v := "balanced"
		dto.NarrativeStance = &v
	}
	if dto.NarrativeStanceSuffix == nil {
		v := ""
		dto.NarrativeStanceSuffix = &v
	}
	if dto.PersistentGuidance == nil {
		v := ""
		dto.PersistentGuidance = &v
	}
	if dto.WakeUpContext == nil {
		v := ""
		dto.WakeUpContext = &v
	}
}

// TrustControlRequest generated from OpenAPI schema.
type TrustControlRequest struct {
	Pinned        *bool `json:"pinned,omitempty"`
	Suppressed    *bool `json:"suppressed,omitempty"`
	UserCorrected *bool `json:"user_corrected,omitempty"`
}

// ValidationError generated from OpenAPI schema.
type ValidationError struct {
	// BLOCKER: ValidationError.properties.ctx: object without properties
	Ctx map[string]any `json:"ctx,omitempty"`
	// BLOCKER: ValidationError.properties.input: untyped property
	Input any `json:"input,omitempty"`
	// BLOCKER: ValidationError.properties.loc.items: non-null union anyOf
	Loc  []json.RawMessage `json:"loc"`
	Msg  string            `json:"msg"`
	Type string            `json:"type"`
}

// WorldRuleSyncRequest generated from OpenAPI schema.
type WorldRuleSyncRequest struct {
	ChatSessionID string `json:"chat_session_id"`
	// PRESENCE: Optional non-null scalar string: absent vs zero-value distinction requires pointer type or custom decode logic when zero is semantically meaningful.
	// DEFAULT: Optional field with default ("apply"): Go handler must apply default when field is absent in request.
	Mode               *string        `json:"mode,omitempty"`
	SupervisorResponse map[string]any `json:"supervisor_response"`
	TurnIndex          *int           `json:"turn_index,omitempty"`
}

// ApplyDefaults applies default values for optional pointer scalar fields in WorldRuleSyncRequest.
func (dto *WorldRuleSyncRequest) ApplyDefaults() {
	if dto.Mode == nil {
		v := "apply"
		dto.Mode = &v
	}
}
